# Generated by Django 3.1.7 on 2021-03-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='video',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
