# Generated by Django 3.1.7 on 2021-03-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0002_auto_20210319_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='video',
            new_name='name',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
