# Generated by Django 3.1.7 on 2021-03-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0003_auto_20210319_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='info_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
